[workspace]
members = ["crates/girlmath", "./bindings/girlmath-js"]
resolver = "2"

[workspace.package]
homepage = "https://github.com/tbd54566975/girlmath"
repository = "https://github.com/tbd54566975/girlmath.git"
license = "MIT"
